export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const REGISTER_ERROR_REMOVE = "REGISTER_ERROR_REMOVE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_ERROR_REMOVE = "LOGIN_ERROR_REMOVE"

export const LOGOUT = "LOGOUT"

export const MESSAGES = "MESSAGES"

export const MY_LEAGUE= "MY_LEAGUE"
export const MY_LEAGUE_ERROR = "MY_LEAGUE_ERROR"

export const MY_LEAGUE_ANNOUNCEMENT= "MY_LEAGUE_ANNOUNCEMENT"
export const MY_LEAGUE_ANNOUNCEMENT_ERROR = "MY_LEAGUE_ANNOUNCEMENT_ERROR"

export const USER_DETAIL = "USER_DETAIL"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"
export const UPDATE_USER_ERROR_REMOVE = "UPDATE_USER_ERROR_REMOVE"

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR"
export const UPDATE_PASSWORD_ERROR_REMOVE = "UPDATE_PASSWORD_ERROR_REMOVE"